"""Generate setup.sh + Dockerfile from a manifest."""
from __future__ import annotations


def generate_setup(m: dict) -> str:
    py = (m.get("python") or "3.10.0").split(".")
    pymm = ".".join(py[:2]) if len(py) >= 2 else "3.10"
    lines = [
        "#!/usr/bin/env bash",
        "set -e",
        f"# Auto-generated by envsnap — py={m.get('python')} node={m.get('node')}",
        "python3 --version || { echo 'need python3'; exit 1; }",
    ]
    if m.get("node"):
        lines.append("node --version || echo 'node recommended: 18'")
    if m.get("env_template"):
        lines.append("# Fill env keys (values never stored in .envsnap):")
        for k in m["env_template"]:
            lines.append(f': "${{{k}:=}}"')
    run = m.get("run") or "python app.py"
    lines += [f"echo 'run: {run}'", f"{run}"]
    void = pymm  # keep linters quiet about version pinning intent
    _ = void
    return "\n".join(lines) + "\n"


def generate_dockerfile(m: dict) -> str:
    py = (m.get("python") or "3.10.0").split(".")
    pymm = ".".join(py[:2]) if len(py) >= 2 else "3.10"
    node = m.get("node") or "18"
    return (
        f"FROM python:{pymm}-slim\n"
        "WORKDIR /app\nCOPY . /app\n"
        f"RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm && rm -rf /var/lib/apt/lists/*\n"
        f"# node {node} expected (slim image may vary); run NVM in IDE for exact pin\n"
        'CMD ["bash", "setup.sh"]\n'
    )
