"""Generate setup.sh + Dockerfile from a manifest."""
from __future__ import annotations


def generate_setup(m: dict) -> str:
    py = (m.get("python") or "3.10.0").split(".")
    lines = [
        "#!/usr/bin/env bash",
        "set -e",
        f"# Auto-generated by envsnap — py={m.get('python')} node={m.get('node')}",
    ]
    node = m.get("node_version") or m.get("node")
    has_py_files = bool(m.get("python_has_app")) or bool(m.get("pip_packages"))
    has_node_files = bool(m.get("node"))
    # node block only if project actually uses node (package.json seen)
    if has_node_files:
        lines += [
            f"# needs node {node}",
            "node --version || echo 'install node 18+ then re-run'",
            "npm ci || npm install",
        ]
    # python block if python files present or no node at all
    if has_py_files or not has_node_files:
        lines += [
            "python3 --version || { echo 'need python3'; exit 1; }",
            "if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
        ]
    if m.get("env_template"):
        lines.append("# Fill env keys (values never stored in .envsnap):")
        for k in m["env_template"]:
            lines.append(f': "${{{k}:=}}"')
    run = m.get("run") or "npm test"
    # gitfox has no dev/start script — fall back to test, not python app.py
    if run == "python app.py" and (m.get("node") and not m.get("python_has_app")):
        run = "npm test"
    lines += [f"echo 'run: {run}'", f"{run}"]
    return "\n".join(lines) + "\n"


def generate_dockerfile(m: dict) -> str:
    py = (m.get("python") or "3.10.0").split(".")
    pymm = ".".join(py[:2]) if len(py) >= 2 else "3.10"
    node = m.get("node") or "18"
    return (
        f"FROM python:{pymm}-slim\n"
        "WORKDIR /app\nCOPY . /app\n"
        f"RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm && rm -rf /var/lib/apt/lists/*\n"
        f"# node {node} expected (slim image may vary); run NVM in IDE for exact pin\n"
        'CMD ["bash", "setup.sh"]\n'
    )
