#!/usr/bin/env bash
set -e
# Auto-generated by envsnap — py=3.14.7 node=v26.9.0
# needs node v26.9.0
node --version || echo 'install node 18+ then re-run'
npm ci || npm install
python3 --version || { echo 'need python3'; exit 1; }
if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
# Fill env keys (values never stored in .envsnap):
: "${OPENAI_KEY:=}"
echo 'run: vite'
vite
